spring:
  application:
    name: english-words-helper

management:
  server:
    port: 9000
  endpoints:
    web:
      exposure:
        include: health,loggers,prometheus,threaddump
  endpoint:
    health:
      probes:
        enabled: true
  health:
    readinessState:
      enabled: true
    livenessState:
      enabled: true
