apiVersion: v1
kind: Service
metadata:
  name: {{ include "service-template.fullname" . }}
  labels:
    {{- include "service-template.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    {{- range .Values.service.ports }}
    - port: {{ .port }}
      targetPort: {{ .targetPort | quote }}
      protocol: {{ .protocol | quote }}
      name: {{ .name | quote }}
    {{- end }}
  selector:
    {{- include "service-template.selectorLabels" . | nindent 4 }}
